variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - deploy

build:
  stage: build
  image: 
    name: klakegg/hugo
    entrypoint: [""]
  script:
    - hugo -e production
  artifacts:
    name: website
    paths:
      - public/
    when: always
    expire_in: 1 week

gcs:
  stage: deploy
  image: google/cloud-sdk:slim
  before_script:
    - gcloud auth activate-service-account --key-file ${GCP_SERVICE_KEY}
    - gcloud config set project ${GCP_PROJECT_ID}
  script:
    - gsutil -m rsync -d -r public/ gs://${GCP_BUCKET}