baseURL: https://bitflipped.dev/
languageCode: en-us
title: BitFlipped Thoughts

theme: hugo-PaperMod
paginate: 5

enableRobotsTXT: true
buildDrafts: true
buildFuture: false
buildExpired: false

pluralizelisttitles: false

minify:
    disableXML: true
    minifyOutput: true
    
params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    description: Thoughts and ponderances from across my brain
    author: BitFlipped <Greg Horejsi>
    comments: true

    highlightjs: true

    ShowReadingTime: true
    ShowShareButtons: true
    comments: false
    defaultTheme: auto
    disableThemeToggle : false
    disableSpecial1stPost : false

    assets:
      favicon: /favicon-32x32.png

    label:
      text: "Home"
      icon: /images/bitflipped.png
      iconHeight: 35

    # profile-mode
    profileMode:
      enabled: false
      title: Flipping the bits, a human perspective...
      imageUrl: /images/bitflipped.png
      # imageTitle: my image
      buttons:
      - name: Posts
        url: posts
      - name: Tutorials
        url: tutorials
      - name: Tags
        url: tags

    # home-info mode
    homeInfoParams:
      Title: Flipping bits, a Human Perspective
      Content: '01000100011100100110010101100001011011010110100101101110011001110010000001101001011011100010000001100011011011110110010001100101001011100010111000101110'

    mainSections:
      - posts
      - tutorials

    socialIcons:
      - name: linkedin
        url: 'https://www.linkedin.com/in/ghorejsi'
      - name: gitlab
        url: 'https://gitlab.com/Bitflipped'
      - name: github
        url: 'https://github.com/BitFlippedCelt'
      - name: buymeacoffee
        url: https://www.buymeacoffee.com/bitflipped

deployment:
  order:
    - .jpg$
    - .gif$
  targets:
    - name: GCS Blog
      URL: gs://bitflipped.dev
  matchers:
    - pattern: ^.+\.(js|css|svg|ttf)$
      cacheControl: 'max-age=31536000, no-transform, public'
      gzip: true
    - pattern: ^.+\.(png|jpg)$
      cacheControl: 'max-age=31536000, no-transform, public'
      gzip: false
    - pattern: ^.+\.(html|xml|json)$
      gzip: true
    